import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/header/HeaderNavbar";
import FooterNavbar from "@/app/_components/footer/FooterNavbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ height: "100vh" }}>
            <header style={{ height: "80px" }}>
                <Navbar/>
            </header>
            <main style={{ height: "calc(100vh - 160px)" }}>
                {children}
            </main>
            <footer style={{ height: "80px" }}>
                <FooterNavbar />
            </footer>
        </body>
        </html>
    );
}
