import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/app/_components/header/HeaderNavbar";
import FooterNavbar from "@/app/_components/footer/FooterNavbar";

export const metadata: Metadata = {
    title: "Pokemon-Wiki",
    description: "Generated by myself xD",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                style={{
                    display: "flex",
                    flexDirection: "column",
                    height: "100vh",
                    overflow: 'hidden',}}>
                <Navbar/>
                <main style={{
                    flex: 1,
                    overflowY: "auto",
                }}>
                    {children}
                </main>
                <FooterNavbar/>
            </body>
        </html>
    );
}
